---
title: "Shift_Map"
output: html_notebook
---

```{r setup}
library(data.table)
library(raster)
library(rgdal)
library(maptools)
library(mapdata)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggmap)
library(maps)
library(sf)


```

```{r import data}
depth <- as.data.table(read.csv("data/poloczanska2013NCC/nceas.999.1_depth.csv"))
range <- as.data.table(read.csv("data/poloczanska2016frontiersmarinescience/table 2_cleaned.csv"))
range[grepl("trailing", Range.edge), Range.edge := "Trailing"]
range$Range.edge <- factor(range$Range.edge)
summary(range)

#just lat and long for depth
depth_latlong <- depth[, c("lat", "long")][, type := "depth"]
range_latlong <- range[, c("Latitude", "Longitude")][, type := "range"]
setnames(range_latlong, old=c("Latitude","Longitude"), new=c("lat", "long"))

latlong_all <- rbind(depth_latlong, range_latlong)

```

```{r map}
library(mapproj)
library(sp)
library(rworldmap)

world <- fortify(spTransform(getMap(), CRS("+proj=wintri")))

coordinates(range_latlong)=~long+lat
proj4string(range_latlong)<- CRS("+proj=longlat +datum=WGS84")
range_latlong.t <- spTransform(range_latlong, CRS("+proj=wintri"))
range_latlong.t <- coordinates(range_latlong.t)

coordinates(depth_latlong)=~long+lat
proj4string(depth_latlong)<- CRS("+proj=longlat +datum=WGS84")
depth_latlong.t <- spTransform(depth_latlong, CRS("+proj=wintri"))
depth_latlong.t <- coordinates(depth_latlong.t)

 
map1 <- ggplot() +
  geom_map(data=world, map=world,
                    aes(x=long, y=lat, map_id=id),
                    color=NA, fill="lightgray") +
   labs(color = "Legend:") +
  geom_point(data = as.data.frame(range_latlong.t), aes(x=long, y=lat, col = "aquamarine3"), size = 2) +
  geom_point(data = as.data.frame(depth_latlong.t), aes(x=long, y=lat, col = "orchid3"), size = 2) +
  theme(legend.position = "right") +
  scale_color_manual(name = "Shift Type", values = c("aquamarine3", "orchid3"),
                       labels = c("Latitudinal Range", "Depth Range")) +
  theme_void()

map1 <- ggplot(world_map) +
  geom_polygon(aes(x=long, y=lat, group = group), fill = "lightgray") +
  coord_map("albers") +
  labs(color = "Legend:") +
  geom_point(data = range_latlong, aes(x=long, y=lat, col = "aquamarine3"), size = 2) +
  geom_point(data = depth_latlong, aes(x=long, y=lat, col = "orchid3"), size = 2) +
  theme(legend.position = "right") +
  scale_color_manual(name = "Shift Type", values = c("aquamarine3", "orchid3"),
                       labels = c("Latitudinal Range", "Depth Range")) +
  theme_void()

map1

ggsave("map1.png", plot = map1, device = NULL, path = "draft_figures")


```

Proportion of species bar plots. We will only need Range.edge and Shift
```{r barplots range}
range_shift <- range[,c("Range.edge", "Shift")][complete.cases(range[,"Shift"])][,Range.edge := factor(Range.edge)]
table(range_shift$Range.edge, range_shift$Shift)
range_shift[, cooler := ifelse(((Range.edge == "Leading" & Shift == "expansion")|(Range.edge == "Centre" & Shift == "expansion") | (Range.edge == "Trailing" & Shift == "contraction")) , 1, 0)]

range_shift[, warmer := ifelse(((Range.edge == "Leading" & Shift == "contraction")|(Range.edge == "Centre" & Shift == "contraction") | (Range.edge == "Trailing" & Shift == "expansion")) , 1, 0)]

range_shift[, nochange := ifelse(Shift == "no change", 1, 0)]
range_shift[, tempchange := as.factor(ifelse(cooler == 1, "Towards cooler", ifelse(warmer == 1, "Towards warmer", "No change")))]


table(range_shift$Range.edge, range_shift$Shift, range_shift$tempchange)

range_shift_summaries <- range_shift %>%
  group_by(Range.edge, tempchange) %>%
  summarize(n=n()) %>%
  mutate(freq = n / sum(n))

#we want non-expansions (no change or contraction) to be below x axis, so these frequencies must be negative
#using data.table
range_shift_summaries <- as.data.table(range_shift_summaries)
range_shift_summaries[, "freq.posneg" := ifelse(tempchange == "Towards warmer" | tempchange == "No change", as.numeric(paste0(freq*(-1))), as.numeric(paste0(freq)))]
range_shift_summaries[, "x.label" := ifelse(Range.edge == "Leading", paste0("Leading \nn=", length(which(range_shift$Range.edge == "Leading"))), 
                                            ifelse(Range.edge == "Trailing", paste0("Trailing \nn=", length(which(range_shift$Range.edge == "Trailing"))), 
                                                   paste0("Centre \nn=", length(which(range_shift$Range.edge == "Centre"))))
                                            )
                      ]
#to help with x axis labeling
range_shift_summaries$x.label <- as.factor(range_shift_summaries$x.label)
x.label.levels <- levels(range_shift_summaries$x.label)

#to reorder coloring in plot for stacks of towards temp changes
range_shift_summaries$tempchange <- factor(range_shift_summaries$tempchange, levels = c("Towards cooler","No change","Towards warmer"))

#make barplot
#to rearrange order of bars
range_shift_summaries$Range.edge <- factor(range_shift_summaries$Range.edge, levels = c("Trailing", "Centre", "Leading"))

plot2 <- ggplot(data = range_shift_summaries, aes(x=Range.edge, y = freq.posneg, fill = tempchange)) +
  geom_bar(stat = "identity", width = 0.7) +
  scale_fill_manual(values = c("cornflowerblue", "darkolivegreen3", "indianred2")) +
  labs(x = "Focal Range Edge", y = "Proportion \nNot Expanding    |    Expanding      ") +
  guides(fill = FALSE) +
  geom_hline(yintercept = 0, col = "black", size = 1) +
  theme_classic() +
  scale_y_continuous(limits = c(-1,1), label = c("1", "0.5", "0", "0.5", "1")) +
  coord_fixed(ratio = 1.7) +
  scale_x_discrete(labels = c(x.label.levels[3], x.label.levels[1], x.label.levels[2])) +
  theme(axis.text = element_text(color = "black", size = 13),  
        axis.title = element_text(color = "black", size = 12),
        legend.title = element_text(color = "black", size = 13, face = 2),
        legend.text = element_text(color = "black", size = 13))

plot2

ggsave("plot2.png", plot = plot2, path = "draft_figures")
#Parking lot
#if we want to have a n for every subgroup
#geom_text(aes(label = n), position = position_stack(vjust = 0.5)) +



```
Proportion of species bar plots. We will only need Deep/Shallower
```{r barplots depth}
depth_shift <- depth[,c("Deeper_shallower")][complete.cases(depth[,"Deeper_shallower"])]
depth_shift[, tempchange := ifelse(Deeper_shallower == "Deeper", "Cooler", ifelse(Deeper_shallower == "Shallower", "Warmer", "No change"))]

depth_shift_summaries <- depth_shift %>%
  group_by(Deeper_shallower, tempchange) %>%
  summarize(n=n()) %>%
  mutate(freq = n/nrow(depth_shift)) %>%
  mutate(label = paste0(Deeper_shallower, '\nN = ', n))

depth_shift_summaries <- as.data.table(depth_shift_summaries)
depth_shift_summaries[, "freq.posneg" := ifelse(tempchange == "Warmer" | tempchange == "No change", as.numeric(paste0(freq*(-1))), as.numeric(paste0(freq)))]

#add dummy x variable for single stack
depth_shift_summaries[, Depth := "depth"]
head(depth_shift_summaries)

plot3 <- ggplot(data = depth_shift_summaries, aes(x = Depth, y = freq.posneg, fill = tempchange)) +
  geom_bar(stat = "identity", width = 0.6) +
  scale_fill_manual(values = c("cornflowerblue", "darkolivegreen3", "indianred2")) +
  labs(x = "  ", y = "Proportion \nNot Expanding    |   Expanding    ", fill = "Direction of \nMovement") +
  geom_hline(yintercept = 0, col = "black", size = 1) +
  theme_classic() +
  scale_y_continuous(limits = c(-1,1), label = c("1", "0.5", "0", "0.5", "1")) +
  scale_x_discrete(label = c("Depth \nN=106\n")) +
  coord_fixed(ratio = 1.7) +
  theme(axis.text.y = element_text(color = "black", size = 13),  
        axis.text.x = element_text(color = "black", size = 13),
        axis.title.x = element_text(color = "black", size = 12),
        axis.title.y = element_blank(),
        legend.title = element_text(color = "black", size = 13, face = 2),
        legend.text = element_text(color = "black", size = 13))
plot3

ggsave("plot3.png", plot = plot3, path = "draft_figures")
```
Combine maps and plots into one
```{r merging}
library(cowplot)
library(grid)
library(gridExtra)
library(ggpubr)
plot_grid(plot2, plot3, labels = c('B', 'C'), nrow = 1, ncol = 2, rel_heights = c(1/1, 1/1))
grid.newpage()
grid.draw(ggplotGrob(plot2), ggplotGrob(plot3))
row2<-grid.arrange(plot2, plot3, ncol = 2)

ggarrange(plot2, plot3, ncol = 2, align = "v")
plot_grid(map1, plot2, plot3, labels = c('B', 'C'), align = "v", nrow = 2, ncol = 2, rel_heights = c(1/2, 1/4, 1/4))

ggarrange(map1,                                                 # First row with scatter plot
          ggarrange(plot2, plot3, labels = c("B", "C")), # Second row with box and dot plots
          nrow = 2, 
          labels = "A"                                        # Labels of the scatter plot
          ) 

grid.arrange(map1, plot2, plot3, nrow = 2, 
             layout_matrix = rbind(c(1,1), c(2,3)))
```

